/**
* @license
* Copyright 2020 Dynatrace LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
 */

package managementzones

import (
	"github.com/dynatrace-oss/terraform-provider-dynatrace/terraform/hcl"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

type AttributeConditions []*AttributeCondition

func (me *AttributeConditions) Schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"condition": {
			Type:        schema.TypeSet,
			Required:    true,
			MinItems:    1,
			Description: "",
			Elem:        &schema.Resource{Schema: new(AttributeCondition).Schema()},
		},
	}
}

func (me AttributeConditions) MarshalHCL(properties hcl.Properties) error {
	return properties.EncodeSlice("condition", me)
}

func (me *AttributeConditions) UnmarshalHCL(decoder hcl.Decoder) error {
	return decoder.DecodeSlice("condition", me)
}

type AttributeCondition struct {
	CaseSensitive    *bool     `json:"caseSensitive,omitempty"`    // Case sensitive
	DynamicKey       *string   `json:"dynamicKey,omitempty"`       // Dynamic key
	DynamicKeySource *string   `json:"dynamicKeySource,omitempty"` // Key source
	EntityID         *string   `json:"entityId,omitempty"`         // Value
	EnumValue        *string   `json:"enumValue,omitempty"`        // Value
	IntegerValue     *int      `json:"integerValue,omitempty"`     // Value
	Key              Attribute `json:"key"`                        // Possible Values: `AZURE_TENANT_UUID`, `EC2_INSTANCE_PRIVATE_HOST_NAME`, `CUSTOM_APPLICATION_TAGS`, `HOST_BITNESS`, `PROCESS_GROUP_DETECTED_NAME`, `APPMON_SERVER_NAME`, `CUSTOM_DEVICE_PORT`, `SERVICE_PORT`, `AWS_APPLICATION_LOAD_BALANCER_TAGS`, `HOST_LOGICAL_CPU_CORES`, `ENTERPRISE_APPLICATION_TAGS`, `SERVICE_DETECTED_NAME`, `PROCESS_GROUP_PREDEFINED_METADATA`, `PROCESS_GROUP_CUSTOM_METADATA`, `OPENSTACK_ACCOUNT_PROJECT_NAME`, `AWS_RELATIONAL_DATABASE_SERVICE_INSTANCE_CLASS`, `CLOUD_FOUNDRY_FOUNDATION_NAME`, `EXTERNAL_MONITOR_TAGS`, `GEOLOCATION_SITE_NAME`, `MOBILE_APPLICATION_PLATFORM`, `OPENSTACK_VM_INSTANCE_TYPE`, `AWS_APPLICATION_LOAD_BALANCER_NAME`, `SERVICE_DATABASE_NAME`, `EXTERNAL_MONITOR_ENGINE_TYPE`, `SERVICE_IBM_CTG_GATEWAY_URL`, `BROWSER_MONITOR_TAGS`, `OPENSTACK_PROJECT_NAME`, `ESXI_HOST_HARDWARE_MODEL`, `EXTERNAL_MONITOR_ENGINE_NAME`, `CLOUD_APPLICATION_NAMESPACE_LABELS`, `DATA_CENTER_SERVICE_PORT`, `EXTERNAL_MONITOR_NAME`, `AWS_CLASSIC_LOAD_BALANCER_NAME`, `SERVICE_TECHNOLOGY`, `SERVICE_WEB_APPLICATION_ID`, `HOST_ARCHITECTURE`, `AWS_AUTO_SCALING_GROUP_TAGS`, `HOST_BOSH_NAME`, `AZURE_MGMT_GROUP_NAME`, `DATA_CENTER_SERVICE_TAGS`, `HOST_GROUP_ID`, `HOST_IP_ADDRESS`, `WEB_APPLICATION_TAGS`, `AZURE_SUBSCRIPTION_NAME`, `CUSTOM_DEVICE_METADATA`, `PROCESS_GROUP_LISTEN_PORT`, `DATA_CENTER_SERVICE_DECODER_TYPE`, `HOST_OS_VERSION`, `AWS_CLASSIC_LOAD_BALANCER_FRONTEND_PORTS`, `CLOUD_APPLICATION_LABELS`, `WEB_APPLICATION_NAME`, `VMWARE_DATACENTER_NAME`, `AZURE_SCALE_SET_NAME`, `PROCESS_GROUP_TECHNOLOGY`, `NAME_OF_COMPUTE_NODE`, `EC2_INSTANCE_AWS_SECURITY_GROUP`, `AWS_RELATIONAL_DATABASE_SERVICE_NAME`, `HOST_CLOUD_TYPE`, `OPENSTACK_VM_NAME`, `AWS_RELATIONAL_DATABASE_SERVICE_ENDPOINT`, `ESXI_HOST_HARDWARE_VENDOR`, `EC2_INSTANCE_AWS_INSTANCE_TYPE`, `DOCKER_FULL_IMAGE_NAME`, `AZURE_ENTITY_TAGS`, `GOOGLE_CLOUD_PLATFORM_ZONE_NAME`, `AWS_ACCOUNT_NAME`, `PROCESS_GROUP_AZURE_SITE_NAME`, `DATA_CENTER_SERVICE_METADATA`, `BROWSER_MONITOR_NAME`, `SERVICE_WEB_CONTEXT_ROOT`, `HOST_AIX_LOGICAL_CPU_COUNT`, `PROCESS_GROUP_NAME`, `DATA_CENTER_SERVICE_IP_ADDRESS`, `SERVICE_PUBLIC_DOMAIN_NAME`, `DATA_CENTER_SERVICE_NAME`, `GOOGLE_COMPUTE_INSTANCE_PUBLIC_IP_ADDRESSES`, `CUSTOM_DEVICE_GROUP_TAGS`, `CUSTOM_DEVICE_GROUP_NAME`, `AWS_RELATIONAL_DATABASE_SERVICE_DB_NAME`, `HOST_KUBERNETES_LABELS`, `EXTERNAL_MONITOR_ENGINE_DESCRIPTION`, `MOBILE_APPLICATION_TAGS`, `SERVICE_DATABASE_TOPOLOGY`, `PROCESS_GROUP_TECHNOLOGY_EDITION`, `EC2_INSTANCE_AMI_ID`, `ESXI_HOST_TAGS`, `AWS_NETWORK_LOAD_BALANCER_NAME`, `QUEUE_NAME`, `VMWARE_VM_NAME`, `PROCESS_GROUP_TAGS`, `SERVICE_CTG_SERVICE_NAME`, `AZURE_REGION_NAME`, `HOST_HYPERVISOR_TYPE`, `GOOGLE_COMPUTE_INSTANCE_MACHINE_TYPE`, `SERVICE_WEB_SERVER_NAME`, `MOBILE_APPLICATION_NAME`, `HOST_PAAS_MEMORY_LIMIT`, `GOOGLE_COMPUTE_INSTANCE_NAME`, `HOST_AZURE_SKU`, `AZURE_VM_NAME`, `QUEUE_TECHNOLOGY`, `EC2_INSTANCE_ID`, `ENTERPRISE_APPLICATION_NAME`, `SERVICE_TECHNOLOGY_EDITION`, `CUSTOM_DEVICE_TECHNOLOGY`, `OPENSTACK_VM_SECURITY_GROUP`, `GOOGLE_COMPUTE_INSTANCE_PROJECT_ID`, `HOST_TECHNOLOGY`, `HOST_CUSTOM_METADATA`, `AZURE_TENANT_NAME`, `DOCKER_CONTAINER_NAME`, `SERVICE_TAGS`, `SERVICE_REMOTE_SERVICE_NAME`, `CUSTOM_APPLICATION_TYPE`, `CLOUD_APPLICATION_NAME`, `HOST_CPU_CORES`, `AWS_NETWORK_LOAD_BALANCER_TAGS`, `CUSTOM_DEVICE_IP_ADDRESS`, `HOST_BOSH_STEMCELL_VERSION`, `HOST_NAME`, `CUSTOM_DEVICE_NAME`, `APPMON_SYSTEM_PROFILE_NAME`, `HOST_AZURE_WEB_APPLICATION_HOST_NAMES`, `HOST_TAGS`, `HOST_BOSH_AVAILABILITY_ZONE`, `WEB_APPLICATION_TYPE`, `CUSTOM_APPLICATION_PLATFORM`, `AWS_RELATIONAL_DATABASE_SERVICE_TAGS`, `ENTERPRISE_APPLICATION_PORT`, `HOST_BOSH_DEPLOYMENT_ID`, `HOST_BOSH_INSTANCE_ID`, `KUBERNETES_NODE_NAME`, `SERVICE_TECHNOLOGY_VERSION`, `CUSTOM_DEVICE_TAGS`, `HOST_GROUP_NAME`, `KUBERNETES_CLUSTER_NAME`, `HOST_AIX_VIRTUAL_CPU_COUNT`, `HTTP_MONITOR_TAGS`, `OPENSTACK_AVAILABILITY_ZONE_NAME`, `SERVICE_WEB_SERVICE_NAME`, `HTTP_MONITOR_NAME`, `SERVICE_AKKA_ACTOR_SYSTEM`, `HOST_AWS_NAME_TAG`, `SERVICE_TOPOLOGY`, `CLOUD_FOUNDRY_ORG_NAME`, `ESXI_HOST_PRODUCT_NAME`, `WEB_APPLICATION_NAME_PATTERN`, `AZURE_MGMT_GROUP_UUID`, `CUSTOM_DEVICE_DNS_ADDRESS`, `GOOGLE_COMPUTE_INSTANCE_ID`, `HOST_AZURE_COMPUTE_MODE`, `SERVICE_ESB_APPLICATION_NAME`, `EC2_INSTANCE_BEANSTALK_ENV_NAME`, `SERVICE_WEB_SERVER_ENDPOINT`, `ENTERPRISE_APPLICATION_IP_ADDRESS`, `QUEUE_VENDOR`, `GOOGLE_COMPUTE_INSTANCE_PROJECT`, `PROCESS_GROUP_AZURE_HOST_NAME`, `HOST_ONEAGENT_CUSTOM_HOST_NAME`, `DOCKER_IMAGE_VERSION`, `OPENSTACK_ACCOUNT_NAME`, `PROCESS_GROUP_TECHNOLOGY_VERSION`, `KUBERNETES_SERVICE_NAME`, `AWS_AUTO_SCALING_GROUP_NAME`, `SERVICE_WEB_SERVICE_NAMESPACE`, `HOST_DETECTED_NAME`, `AZURE_ENTITY_NAME`, `AZURE_SUBSCRIPTION_UUID`, `AWS_CLASSIC_LOAD_BALANCER_TAGS`, `HOST_BOSH_INSTANCE_NAME`, `AWS_AVAILABILITY_ZONE_NAME`, `SERVICE_TYPE`, `ENTERPRISE_APPLICATION_DECODER_TYPE`, `SERVICE_DATABASE_VENDOR`, `ESXI_HOST_CLUSTER_NAME`, `EC2_INSTANCE_PUBLIC_HOST_NAME`, `AWS_ACCOUNT_ID`, `SERVICE_MESSAGING_LISTENER_CLASS_NAME`, `SERVICE_REMOTE_ENDPOINT`, `AWS_RELATIONAL_DATABASE_SERVICE_PORT`, `ESXI_HOST_NAME`, `OPENSTACK_REGION_NAME`, `PROCESS_GROUP_ID`, `HOST_AIX_SIMULTANEOUS_THREADS`, `CLOUD_APPLICATION_NAMESPACE_NAME`, `ESXI_HOST_PRODUCT_VERSION`, `SERVICE_DATABASE_HOST_NAME`, `HOST_PAAS_TYPE`, `EC2_INSTANCE_TAGS`, `CUSTOM_APPLICATION_NAME`, `HOST_AZURE_WEB_APPLICATION_SITE_NAMES`, `EC2_INSTANCE_NAME`, `SERVICE_NAME`, `ENTERPRISE_APPLICATION_METADATA`, `AWS_RELATIONAL_DATABASE_SERVICE_ENGINE`, `HOST_OS_TYPE`
	Operator         Operator  `json:"operator"`                   // Possible Values: `NOT_BEGINS_WITH`, `TAG_KEY_EQUALS`, `EQUALS`, `EXISTS`, `BEGINS_WITH`, `IS_IP_IN_RANGE`, `NOT_EQUALS`, `GREATER_THAN`, `LOWER_THAN`, `NOT_LOWER_THAN_OR_EQUAL`, `NOT_GREATER_THAN`, `GREATER_THAN_OR_EQUAL`, `REGEX_MATCHES`, `NOT_LOWER_THAN`, `NOT_ENDS_WITH`, `NOT_TAG_KEY_EQUALS`, `NOT_REGEX_MATCHES`, `CONTAINS`, `NOT_EXISTS`, `NOT_GREATER_THAN_OR_EQUAL`, `NOT_IS_IP_IN_RANGE`, `NOT_CONTAINS`, `LOWER_THAN_OR_EQUAL`, `ENDS_WITH`
	StringValue      *string   `json:"stringValue,omitempty"`      // Value
	Tag              *string   `json:"tag,omitempty"`              // Format: `[CONTEXT]tagKey:tagValue`
}

func (me *AttributeCondition) Schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"case_sensitive": {
			Type:        schema.TypeBool,
			Description: "Case sensitive",
			Optional:    true,
		},
		"dynamic_key": {
			Type:        schema.TypeString,
			Description: "Dynamic key",
			Optional:    true,
		},
		"dynamic_key_source": {
			Type:        schema.TypeString,
			Description: "Key source",
			Optional:    true,
		},
		"entity_id": {
			Type:        schema.TypeString,
			Description: "Value",
			Optional:    true,
		},
		"enum_value": {
			Type:        schema.TypeString,
			Description: "Value",
			Optional:    true,
		},
		"integer_value": {
			Type:        schema.TypeInt,
			Description: "Value",
			Optional:    true,
		},
		"key": {
			Type:        schema.TypeString,
			Description: "Possible Values: `AZURE_TENANT_UUID`, `EC2_INSTANCE_PRIVATE_HOST_NAME`, `CUSTOM_APPLICATION_TAGS`, `HOST_BITNESS`, `PROCESS_GROUP_DETECTED_NAME`, `APPMON_SERVER_NAME`, `CUSTOM_DEVICE_PORT`, `SERVICE_PORT`, `AWS_APPLICATION_LOAD_BALANCER_TAGS`, `HOST_LOGICAL_CPU_CORES`, `ENTERPRISE_APPLICATION_TAGS`, `SERVICE_DETECTED_NAME`, `PROCESS_GROUP_PREDEFINED_METADATA`, `PROCESS_GROUP_CUSTOM_METADATA`, `OPENSTACK_ACCOUNT_PROJECT_NAME`, `AWS_RELATIONAL_DATABASE_SERVICE_INSTANCE_CLASS`, `CLOUD_FOUNDRY_FOUNDATION_NAME`, `EXTERNAL_MONITOR_TAGS`, `GEOLOCATION_SITE_NAME`, `MOBILE_APPLICATION_PLATFORM`, `OPENSTACK_VM_INSTANCE_TYPE`, `AWS_APPLICATION_LOAD_BALANCER_NAME`, `SERVICE_DATABASE_NAME`, `EXTERNAL_MONITOR_ENGINE_TYPE`, `SERVICE_IBM_CTG_GATEWAY_URL`, `BROWSER_MONITOR_TAGS`, `OPENSTACK_PROJECT_NAME`, `ESXI_HOST_HARDWARE_MODEL`, `EXTERNAL_MONITOR_ENGINE_NAME`, `CLOUD_APPLICATION_NAMESPACE_LABELS`, `DATA_CENTER_SERVICE_PORT`, `EXTERNAL_MONITOR_NAME`, `AWS_CLASSIC_LOAD_BALANCER_NAME`, `SERVICE_TECHNOLOGY`, `SERVICE_WEB_APPLICATION_ID`, `HOST_ARCHITECTURE`, `AWS_AUTO_SCALING_GROUP_TAGS`, `HOST_BOSH_NAME`, `AZURE_MGMT_GROUP_NAME`, `DATA_CENTER_SERVICE_TAGS`, `HOST_GROUP_ID`, `HOST_IP_ADDRESS`, `WEB_APPLICATION_TAGS`, `AZURE_SUBSCRIPTION_NAME`, `CUSTOM_DEVICE_METADATA`, `PROCESS_GROUP_LISTEN_PORT`, `DATA_CENTER_SERVICE_DECODER_TYPE`, `HOST_OS_VERSION`, `AWS_CLASSIC_LOAD_BALANCER_FRONTEND_PORTS`, `CLOUD_APPLICATION_LABELS`, `WEB_APPLICATION_NAME`, `VMWARE_DATACENTER_NAME`, `AZURE_SCALE_SET_NAME`, `PROCESS_GROUP_TECHNOLOGY`, `NAME_OF_COMPUTE_NODE`, `EC2_INSTANCE_AWS_SECURITY_GROUP`, `AWS_RELATIONAL_DATABASE_SERVICE_NAME`, `HOST_CLOUD_TYPE`, `OPENSTACK_VM_NAME`, `AWS_RELATIONAL_DATABASE_SERVICE_ENDPOINT`, `ESXI_HOST_HARDWARE_VENDOR`, `EC2_INSTANCE_AWS_INSTANCE_TYPE`, `DOCKER_FULL_IMAGE_NAME`, `AZURE_ENTITY_TAGS`, `GOOGLE_CLOUD_PLATFORM_ZONE_NAME`, `AWS_ACCOUNT_NAME`, `PROCESS_GROUP_AZURE_SITE_NAME`, `DATA_CENTER_SERVICE_METADATA`, `BROWSER_MONITOR_NAME`, `SERVICE_WEB_CONTEXT_ROOT`, `HOST_AIX_LOGICAL_CPU_COUNT`, `PROCESS_GROUP_NAME`, `DATA_CENTER_SERVICE_IP_ADDRESS`, `SERVICE_PUBLIC_DOMAIN_NAME`, `DATA_CENTER_SERVICE_NAME`, `GOOGLE_COMPUTE_INSTANCE_PUBLIC_IP_ADDRESSES`, `CUSTOM_DEVICE_GROUP_TAGS`, `CUSTOM_DEVICE_GROUP_NAME`, `AWS_RELATIONAL_DATABASE_SERVICE_DB_NAME`, `HOST_KUBERNETES_LABELS`, `EXTERNAL_MONITOR_ENGINE_DESCRIPTION`, `MOBILE_APPLICATION_TAGS`, `SERVICE_DATABASE_TOPOLOGY`, `PROCESS_GROUP_TECHNOLOGY_EDITION`, `EC2_INSTANCE_AMI_ID`, `ESXI_HOST_TAGS`, `AWS_NETWORK_LOAD_BALANCER_NAME`, `QUEUE_NAME`, `VMWARE_VM_NAME`, `PROCESS_GROUP_TAGS`, `SERVICE_CTG_SERVICE_NAME`, `AZURE_REGION_NAME`, `HOST_HYPERVISOR_TYPE`, `GOOGLE_COMPUTE_INSTANCE_MACHINE_TYPE`, `SERVICE_WEB_SERVER_NAME`, `MOBILE_APPLICATION_NAME`, `HOST_PAAS_MEMORY_LIMIT`, `GOOGLE_COMPUTE_INSTANCE_NAME`, `HOST_AZURE_SKU`, `AZURE_VM_NAME`, `QUEUE_TECHNOLOGY`, `EC2_INSTANCE_ID`, `ENTERPRISE_APPLICATION_NAME`, `SERVICE_TECHNOLOGY_EDITION`, `CUSTOM_DEVICE_TECHNOLOGY`, `OPENSTACK_VM_SECURITY_GROUP`, `GOOGLE_COMPUTE_INSTANCE_PROJECT_ID`, `HOST_TECHNOLOGY`, `HOST_CUSTOM_METADATA`, `AZURE_TENANT_NAME`, `DOCKER_CONTAINER_NAME`, `SERVICE_TAGS`, `SERVICE_REMOTE_SERVICE_NAME`, `CUSTOM_APPLICATION_TYPE`, `CLOUD_APPLICATION_NAME`, `HOST_CPU_CORES`, `AWS_NETWORK_LOAD_BALANCER_TAGS`, `CUSTOM_DEVICE_IP_ADDRESS`, `HOST_BOSH_STEMCELL_VERSION`, `HOST_NAME`, `CUSTOM_DEVICE_NAME`, `APPMON_SYSTEM_PROFILE_NAME`, `HOST_AZURE_WEB_APPLICATION_HOST_NAMES`, `HOST_TAGS`, `HOST_BOSH_AVAILABILITY_ZONE`, `WEB_APPLICATION_TYPE`, `CUSTOM_APPLICATION_PLATFORM`, `AWS_RELATIONAL_DATABASE_SERVICE_TAGS`, `ENTERPRISE_APPLICATION_PORT`, `HOST_BOSH_DEPLOYMENT_ID`, `HOST_BOSH_INSTANCE_ID`, `KUBERNETES_NODE_NAME`, `SERVICE_TECHNOLOGY_VERSION`, `CUSTOM_DEVICE_TAGS`, `HOST_GROUP_NAME`, `KUBERNETES_CLUSTER_NAME`, `HOST_AIX_VIRTUAL_CPU_COUNT`, `HTTP_MONITOR_TAGS`, `OPENSTACK_AVAILABILITY_ZONE_NAME`, `SERVICE_WEB_SERVICE_NAME`, `HTTP_MONITOR_NAME`, `SERVICE_AKKA_ACTOR_SYSTEM`, `HOST_AWS_NAME_TAG`, `SERVICE_TOPOLOGY`, `CLOUD_FOUNDRY_ORG_NAME`, `ESXI_HOST_PRODUCT_NAME`, `WEB_APPLICATION_NAME_PATTERN`, `AZURE_MGMT_GROUP_UUID`, `CUSTOM_DEVICE_DNS_ADDRESS`, `GOOGLE_COMPUTE_INSTANCE_ID`, `HOST_AZURE_COMPUTE_MODE`, `SERVICE_ESB_APPLICATION_NAME`, `EC2_INSTANCE_BEANSTALK_ENV_NAME`, `SERVICE_WEB_SERVER_ENDPOINT`, `ENTERPRISE_APPLICATION_IP_ADDRESS`, `QUEUE_VENDOR`, `GOOGLE_COMPUTE_INSTANCE_PROJECT`, `PROCESS_GROUP_AZURE_HOST_NAME`, `HOST_ONEAGENT_CUSTOM_HOST_NAME`, `DOCKER_IMAGE_VERSION`, `OPENSTACK_ACCOUNT_NAME`, `PROCESS_GROUP_TECHNOLOGY_VERSION`, `KUBERNETES_SERVICE_NAME`, `AWS_AUTO_SCALING_GROUP_NAME`, `SERVICE_WEB_SERVICE_NAMESPACE`, `HOST_DETECTED_NAME`, `AZURE_ENTITY_NAME`, `AZURE_SUBSCRIPTION_UUID`, `AWS_CLASSIC_LOAD_BALANCER_TAGS`, `HOST_BOSH_INSTANCE_NAME`, `AWS_AVAILABILITY_ZONE_NAME`, `SERVICE_TYPE`, `ENTERPRISE_APPLICATION_DECODER_TYPE`, `SERVICE_DATABASE_VENDOR`, `ESXI_HOST_CLUSTER_NAME`, `EC2_INSTANCE_PUBLIC_HOST_NAME`, `AWS_ACCOUNT_ID`, `SERVICE_MESSAGING_LISTENER_CLASS_NAME`, `SERVICE_REMOTE_ENDPOINT`, `AWS_RELATIONAL_DATABASE_SERVICE_PORT`, `ESXI_HOST_NAME`, `OPENSTACK_REGION_NAME`, `PROCESS_GROUP_ID`, `HOST_AIX_SIMULTANEOUS_THREADS`, `CLOUD_APPLICATION_NAMESPACE_NAME`, `ESXI_HOST_PRODUCT_VERSION`, `SERVICE_DATABASE_HOST_NAME`, `HOST_PAAS_TYPE`, `EC2_INSTANCE_TAGS`, `CUSTOM_APPLICATION_NAME`, `HOST_AZURE_WEB_APPLICATION_SITE_NAMES`, `EC2_INSTANCE_NAME`, `SERVICE_NAME`, `ENTERPRISE_APPLICATION_METADATA`, `AWS_RELATIONAL_DATABASE_SERVICE_ENGINE`, `HOST_OS_TYPE`",
			Required:    true,
		},
		"operator": {
			Type:        schema.TypeString,
			Description: "Possible Values: `NOT_BEGINS_WITH`, `TAG_KEY_EQUALS`, `EQUALS`, `EXISTS`, `BEGINS_WITH`, `IS_IP_IN_RANGE`, `NOT_EQUALS`, `GREATER_THAN`, `LOWER_THAN`, `NOT_LOWER_THAN_OR_EQUAL`, `NOT_GREATER_THAN`, `GREATER_THAN_OR_EQUAL`, `REGEX_MATCHES`, `NOT_LOWER_THAN`, `NOT_ENDS_WITH`, `NOT_TAG_KEY_EQUALS`, `NOT_REGEX_MATCHES`, `CONTAINS`, `NOT_EXISTS`, `NOT_GREATER_THAN_OR_EQUAL`, `NOT_IS_IP_IN_RANGE`, `NOT_CONTAINS`, `LOWER_THAN_OR_EQUAL`, `ENDS_WITH`",
			Required:    true,
		},
		"string_value": {
			Type:        schema.TypeString,
			Description: "Value",
			Optional:    true,
		},
		"tag": {
			Type:        schema.TypeString,
			Description: "Format: `[CONTEXT]tagKey:tagValue`",
			Optional:    true,
		},
	}
}

func (me *AttributeCondition) MarshalHCL(properties hcl.Properties) error {
	return properties.EncodeAll(map[string]any{
		"case_sensitive":     me.CaseSensitive,
		"dynamic_key":        me.DynamicKey,
		"dynamic_key_source": me.DynamicKeySource,
		"entity_id":          me.EntityID,
		"enum_value":         me.EnumValue,
		"integer_value":      me.IntegerValue,
		"key":                me.Key,
		"operator":           me.Operator,
		"string_value":       me.StringValue,
		"tag":                me.Tag,
	})
}

func (me *AttributeCondition) UnmarshalHCL(decoder hcl.Decoder) error {
	return decoder.DecodeAll(map[string]any{
		"case_sensitive":     &me.CaseSensitive,
		"dynamic_key":        &me.DynamicKey,
		"dynamic_key_source": &me.DynamicKeySource,
		"entity_id":          &me.EntityID,
		"enum_value":         &me.EnumValue,
		"integer_value":      &me.IntegerValue,
		"key":                &me.Key,
		"operator":           &me.Operator,
		"string_value":       &me.StringValue,
		"tag":                &me.Tag,
	})
}
