/**
* @license
* Copyright 2020 Dynatrace LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
 */

package profile

import (
	"github.com/dynatrace-oss/terraform-provider-dynatrace/terraform/hcl"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
)

type PredefinedEventFilter struct {
	EventType EventType `json:"eventType"` // Possible Values: `PROCESS_NA_HIGH_CONN_FAIL_RATE`, `MOBILE_APPLICATION_UNEXPECTED_LOW_LOAD`, `RDS_LOW_STORAGE_SPACE`, `OSI_HIGH_CPU`, `PROCESS_HIGH_GC_ACTIVITY`, `SYNTHETIC_GLOBAL_OUTAGE`, `SERVICE_UNEXPECTED_HIGH_LOAD`, `EBS_VOLUME_HIGH_LATENCY`, `OSI_SLOW_DISK`, `ESXI_VM_IMPACT_HOST_MEMORY_SATURATION`, `ESXI_HOST_DISK_QUEUE_SLOW`, `ESXI_HOST_NETWORK_PROBLEMS`, `APPLICATION_ERROR_RATE_INCREASED`, `MOBILE_APP_CRASH_RATE_INCREASED`, `SYNTHETIC_PRIVATE_LOCATION_OUTAGE`, `OSI_UNEXPECTEDLY_UNAVAILABLE`, `RDS_LOW_MEMORY`, `APPLICATION_SLOWDOWN`, `SERVICE_SLOWDOWN`, `OSI_GRACEFULLY_SHUTDOWN`, `APPLICATION_UNEXPECTED_HIGH_LOAD`, `OSI_HIGH_MEMORY`, `ESXI_HOST_MEMORY_SATURATION`, `APPLICATION_UNEXPECTED_LOW_LOAD`, `ESXI_VM_IMPACT_HOST_CPU_SATURATION`, `OSI_NIC_DROPPED_PACKETS_HIGH`, `PROCESS_NA_HIGH_LOSS_RATE`, `CUSTOM_APP_CRASH_RATE_INCREASED`, `SYNTHETIC_LOCAL_OUTAGE`, `OSI_NIC_UTILIZATION_HIGH`, `SERVICE_ERROR_RATE_INCREASED`, `ESXI_HOST_DATASTORE_LOW_DISK_SPACE`, `RDS_RESTART_SEQUENCE`, `ESXI_HOST_CPU_SATURATION`, `OSI_DISK_LOW_INODES`, `ESXI_HOST_OVERLOADED_STORAGE`, `DATABASE_CONNECTION_FAILURE`, `HTTP_CHECK_GLOBAL_OUTAGE`, `ELB_HIGH_BACKEND_ERROR_RATE`, `PROCESS_MEMORY_RESOURCE_EXHAUSTED`, `EXTERNAL_SYNTHETIC_TEST_SLOWDOWN`, `CUSTOM_APPLICATION_UNEXPECTED_HIGH_LOAD`, `HOST_OF_SERVICE_UNAVAILABLE`, `PROCESS_THREADS_RESOURCE_EXHAUSTED`, `CUSTOM_APPLICATION_SLOWDOWN`, `OSI_NIC_ERRORS_HIGH`, `PGI_UNAVAILABLE`, `SYNTHETIC_NODE_OUTAGE`, `MOBILE_APPLICATION_UNEXPECTED_HIGH_LOAD`, `RDS_HIGH_LATENCY`, `CUSTOM_APPLICATION_UNEXPECTED_LOW_LOAD`, `HTTP_CHECK_TEST_LOCATION_SLOWDOWN`, `PG_LOW_INSTANCE_COUNT`, `SYNTHETIC_TEST_LOCATION_SLOWDOWN`, `MOBILE_APPLICATION_SLOWDOWN`, `EC2_HIGH_CPU`, `CUSTOM_APPLICATION_ERROR_RATE_INCREASED`, `ESXI_GUEST_ACTIVE_SWAP_WAIT`, `MONITORING_UNAVAILABLE`, `AWS_LAMBDA_HIGH_ERROR_RATE`, `PROCESS_CRASHED`, `RDS_OF_SERVICE_UNAVAILABLE`, `MOBILE_APPLICATION_ERROR_RATE_INCREASED`, `ESXI_GUEST_CPU_LIMIT_REACHED`, `OSI_LOW_DISK_SPACE`, `HTTP_CHECK_LOCAL_OUTAGE`, `EXTERNAL_SYNTHETIC_TEST_OUTAGE`, `SERVICE_UNEXPECTED_LOW_LOAD`, `RDS_HIGH_CPU`, `ESXI_HOST_DISK_SLOW`, `PGI_OF_SERVICE_UNAVAILABLE`
	Negate    bool      `json:"negate"`
}

func (me *PredefinedEventFilter) Schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"event_type": {
			Type:        schema.TypeString,
			Description: "Possible Values: `PROCESS_NA_HIGH_CONN_FAIL_RATE`, `MOBILE_APPLICATION_UNEXPECTED_LOW_LOAD`, `RDS_LOW_STORAGE_SPACE`, `OSI_HIGH_CPU`, `PROCESS_HIGH_GC_ACTIVITY`, `SYNTHETIC_GLOBAL_OUTAGE`, `SERVICE_UNEXPECTED_HIGH_LOAD`, `EBS_VOLUME_HIGH_LATENCY`, `OSI_SLOW_DISK`, `ESXI_VM_IMPACT_HOST_MEMORY_SATURATION`, `ESXI_HOST_DISK_QUEUE_SLOW`, `ESXI_HOST_NETWORK_PROBLEMS`, `APPLICATION_ERROR_RATE_INCREASED`, `MOBILE_APP_CRASH_RATE_INCREASED`, `SYNTHETIC_PRIVATE_LOCATION_OUTAGE`, `OSI_UNEXPECTEDLY_UNAVAILABLE`, `RDS_LOW_MEMORY`, `APPLICATION_SLOWDOWN`, `SERVICE_SLOWDOWN`, `OSI_GRACEFULLY_SHUTDOWN`, `APPLICATION_UNEXPECTED_HIGH_LOAD`, `OSI_HIGH_MEMORY`, `ESXI_HOST_MEMORY_SATURATION`, `APPLICATION_UNEXPECTED_LOW_LOAD`, `ESXI_VM_IMPACT_HOST_CPU_SATURATION`, `OSI_NIC_DROPPED_PACKETS_HIGH`, `PROCESS_NA_HIGH_LOSS_RATE`, `CUSTOM_APP_CRASH_RATE_INCREASED`, `SYNTHETIC_LOCAL_OUTAGE`, `OSI_NIC_UTILIZATION_HIGH`, `SERVICE_ERROR_RATE_INCREASED`, `ESXI_HOST_DATASTORE_LOW_DISK_SPACE`, `RDS_RESTART_SEQUENCE`, `ESXI_HOST_CPU_SATURATION`, `OSI_DISK_LOW_INODES`, `ESXI_HOST_OVERLOADED_STORAGE`, `DATABASE_CONNECTION_FAILURE`, `HTTP_CHECK_GLOBAL_OUTAGE`, `ELB_HIGH_BACKEND_ERROR_RATE`, `PROCESS_MEMORY_RESOURCE_EXHAUSTED`, `EXTERNAL_SYNTHETIC_TEST_SLOWDOWN`, `CUSTOM_APPLICATION_UNEXPECTED_HIGH_LOAD`, `HOST_OF_SERVICE_UNAVAILABLE`, `PROCESS_THREADS_RESOURCE_EXHAUSTED`, `CUSTOM_APPLICATION_SLOWDOWN`, `OSI_NIC_ERRORS_HIGH`, `PGI_UNAVAILABLE`, `SYNTHETIC_NODE_OUTAGE`, `MOBILE_APPLICATION_UNEXPECTED_HIGH_LOAD`, `RDS_HIGH_LATENCY`, `CUSTOM_APPLICATION_UNEXPECTED_LOW_LOAD`, `HTTP_CHECK_TEST_LOCATION_SLOWDOWN`, `PG_LOW_INSTANCE_COUNT`, `SYNTHETIC_TEST_LOCATION_SLOWDOWN`, `MOBILE_APPLICATION_SLOWDOWN`, `EC2_HIGH_CPU`, `CUSTOM_APPLICATION_ERROR_RATE_INCREASED`, `ESXI_GUEST_ACTIVE_SWAP_WAIT`, `MONITORING_UNAVAILABLE`, `AWS_LAMBDA_HIGH_ERROR_RATE`, `PROCESS_CRASHED`, `RDS_OF_SERVICE_UNAVAILABLE`, `MOBILE_APPLICATION_ERROR_RATE_INCREASED`, `ESXI_GUEST_CPU_LIMIT_REACHED`, `OSI_LOW_DISK_SPACE`, `HTTP_CHECK_LOCAL_OUTAGE`, `EXTERNAL_SYNTHETIC_TEST_OUTAGE`, `SERVICE_UNEXPECTED_LOW_LOAD`, `RDS_HIGH_CPU`, `ESXI_HOST_DISK_SLOW`, `PGI_OF_SERVICE_UNAVAILABLE`",
			Required:    true,
		},
		"negate": {
			Type:        schema.TypeBool,
			Description: "no documentation available",
			Required:    true,
		},
	}
}

func (me *PredefinedEventFilter) MarshalHCL(properties hcl.Properties) error {
	return properties.EncodeAll(map[string]any{
		"event_type": me.EventType,
		"negate":     me.Negate,
	})
}

func (me *PredefinedEventFilter) UnmarshalHCL(decoder hcl.Decoder) error {
	return decoder.DecodeAll(map[string]any{
		"event_type": &me.EventType,
		"negate":     &me.Negate,
	})
}
